import Head from "next/head";
import Image from "next/image";
import styles from "../styles/home.module.scss";

import Button from "@mui/material/Button";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;400;600&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;400;600&family=PT+Serif:ital,wght@0,400;0,700;1,400;1,700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <div className={styles.main}>
        <h2 className={styles.title}>
          Welcome to the beggining of CLU's website.
        </h2>
        <h3 className={styles.subtitle}>These are the two chosen fonts.</h3>
        <div>
          <Button variant="contained" color="primary">
            See you tomorrow!
          </Button>
        </div>
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </div>
    </div>
  );
}
